facebook_app_id: "example"
facebook_app_secret: "example"
twitter_app_id: "example"
twitter_app_secret: "example"
googleauth2_app_id: "example"
googleauth2_app_secret: "example"
linkedin_app_id: "example"
linkedin_app_secret: "example"