development:
  adapter: postgresql
  encoding: unicode
  database: raim_development
  host: localhost
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: raim_test
  host: localhost
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: raim_production
  host: localhost
  pool: 5
  username:
  password:
